server:
  port: 8001

spring:
  application:
    name: consumer01

eureka:
  client:                                                   #客户端注册进eureka服务列表内
    service-url:
#      单机
      defaultZone: http://localhost:7002/eureka

      #集群是
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka/
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: consumer01
    prefer-ip-address: true                                  #访问路径可以显示IP地址




