server:
  port: 8002

spring:
  application:
    name: producer

eureka:
  client:                                                   #客户端注册进eureka服务列表内
    service-url:
#      单机
      defaultZone: http://localhost:7002/eureka

      #集群是
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka/
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: producer01
    prefer-ip-address: true                                  #访问路径可以显示IP地址

info:                                                         #在Eure页面访问info返回的信息的配置
  app.name: producer01
  company.name: song.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


